const assignNoteForDistrict = (stationName) => {
  switch (stationName) {
    case 'Upminster':
      return 'C1';
    case 'UpminsterBridge':
      return 'D1';
    case 'Hornchurch':
      return 'E1';
    case 'ElmPark':
      return 'G1';
    case 'DagenhamEast':
      return 'A1';
    case 'DagenhamHeathway':
      return 'C2';
    case 'Becontree':
      return 'D2';
    case 'Upney':
      return 'E2';
    case 'Barking':
      return 'G2';
    case 'EastHam':
      return 'A2';
    case 'UptonPark':
      return 'C3';
    case 'Plaistow':
      return 'D1';
    case 'WestHam':
      return 'E1';
    case 'Bromley-by-Bow':
      return 'G1';
    case 'BowRoad':
      return 'A1';
    case 'MileEnd':
      return 'C3';
    case 'StepneyGreen':
      return 'C2';
    case 'Whitechapel':
      return 'D2';
    case 'AldgateEast':
      return 'E2';
    case 'TowerHill':
      return 'G2';
    case 'Monument':
      return 'A2';
    case 'CannonStreet':
      return 'C1';
    case 'MansionHouse':
      return 'D1';
    case 'Blackfriars':
      return 'E1';
    case 'Temple':
      return 'G1';
    case 'Embankment':
      return 'A2';
    case 'Westminster':
      return 'C2';
    case 'StJamessPark':
      return 'D2';
    case 'Victoria':
      return 'E2';
    case 'SloaneSquare':
      return 'G2';
    case 'SouthKensington':
      return 'A2';
    case 'GloucesterRoad':
      return 'C3';
    case 'HighStreetKensington':
      return 'C1';
    case 'EarlsCourt':
      return 'D1';
    case 'WestKensington':
      return 'E1';
    case 'BaronsCourt':
      return 'G1';
    case 'Hammersmith(Dist&PiccLine)':
      return 'A1';
    case 'RavenscourtPark':
      return 'C2';
    case 'StamfordBrook':
      return 'D2';
    case 'TurnhamGreen':
      return 'E2';
    case 'Gunnersbury':
      return 'G2';
    case 'KewGardens':
      return 'A2';
    case 'Richmond':
      return 'C3';
    case 'WimbledonPark':
      return 'D1';
    case 'Wimbledon':
      return 'E1';
    case 'WestBrompton':
      return 'G1';
    default:
      return 'C2';
  }
};

export default assignNoteForDistrict;
